In [102]:
%load_ext cudf.pandas
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

The cudf.pandas extension is already loaded. To reload it, use:
  %reload_ext cudf.pandas

In [103]:
df1 = pd.read_csv('/kaggle/input/datasets/ashura369/financial-dataset/clients.csv')
df2 = pd.read_csv('/kaggle/input/datasets/ashura369/financial-dataset/properties.csv')

In [104]:
print(df1.shape)
df1.head(5)

(2000, 12)

,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,C0001,Individual,Kareem,Liu,05-11-1968,F,USA,California,Home,4,Yes,Website
1,C0002,Individual,Trystan,Oconnor,11/26/1962,M,USA,California,Home,1,No,Website
2,C0003,Individual,Kale,Gay,04-07-1959,M,USA,California,Home,4,Yes,Agency
3,C0004,Individual,Russell,Gross,11/25/1959,M,USA,California,Home,5,No,Website
4,C0005,Company,Marleez,Co,2/28/1976,M,USA,California,Investment,5,No,Website

In [105]:
print(df2.shape)
df2.head(5)

(10000, 9)

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref
0,1012,1,01-01-2024,Apartment,12,1160.36,"$300,385.62",Sold,C0027
1,1015,1,01-01-2024,Apartment,15,782.25,"$208,930.81",Sold,C0097
2,1021,1,01-01-2024,Apartment,21,756.21,"$218,585.92",Sold,C0113
3,1030,1,01-01-2024,Apartment,30,743.09,"$246,172.68",Sold,C0141
4,2016,2,01-01-2024,Apartment,16,701.66,"$212,265.67",Sold,C0146

Since both `df1` and `df2` datasets have `client_id` and `client_ref` in common, so we will be merging them.

In [106]:
df = pd.merge(df1,df2, left_on='client_id', right_on='client_ref', how='right')

In [107]:
print(df.shape)
with pd.option_context('display.max_columns', None):
    display(df.head(6))

(10000, 21)

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,1012,1,01-01-2024,Apartment,12,1160.36,"$300,385.62",Sold,C0027,C0027,Individual,Grant,Weber,09-08-1968,M,USA,California,Home,5,Yes,Website
1,1015,1,01-01-2024,Apartment,15,782.25,"$208,930.81",Sold,C0097,C0097,Individual,Franklin,Mack,6/18/1943,M,USA,Virginia,Home,5,Yes,Website
2,1021,1,01-01-2024,Apartment,21,756.21,"$218,585.92",Sold,C0113,C0113,Individual,Arthur,Bray,7/14/1949,M,USA,Utah,Investment,4,No,Agency
3,1030,1,01-01-2024,Apartment,30,743.09,"$246,172.68",Sold,C0141,C0141,Individual,Madalyn,Mercer,6/21/1986,F,USA,California,Home,5,No,Website
4,2016,2,01-01-2024,Apartment,16,701.66,"$212,265.67",Sold,C0146,C0146,Individual,Hazel,Ayers,02-01-1963,M,USA,Colorado,Home,2,No,Website
5,2018,2,01-01-2024,Apartment,18,927.83,"$275,394.25",Sold,C0023,C0023,Individual,Cole,Taylor,12-06-1958,M,USA,California,Home,3,Yes,Website

In [108]:
# df.to_csv('Full Dataset.csv', index=False)

In [109]:
print(f"COLUMNS NAMES : \n {df.columns}\n\n")

COLUMNS NAMES :
 Index(['listing_id', 'tower_number', 'transaction_date', 'unit_category',
       'unit_number', 'floor_area_sqft', 'sale_price', 'listing_status',
       'client_ref', 'client_id', 'client_type', 'first_name', 'last_name',
       'date_of_birth', 'gender', 'country', 'region', 'acquisition_purpose',
       'satisfaction_score', 'loan_applied', 'referral_channel'],
      dtype='object')

In [110]:
df.isna().sum().reset_index()

                  index     0
0            listing_id     0
1          tower_number     0
2      transaction_date     0
3         unit_category     0
4           unit_number     0
5       floor_area_sqft     0
6            sale_price     0
7        listing_status     0
8            client_ref  2695
9             client_id  2695
10          client_type  2695
11           first_name  2695
12            last_name  2695
13        date_of_birth  2695
14               gender  2695
15              country  2695
16               region  2695
17  acquisition_purpose  2695
18   satisfaction_score  2695
19         loan_applied  2695
20     referral_channel  2695

In [111]:
with pd.option_context('display.max_columns', None):
    display(df[df.isna().any(axis=1)])

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
11,4039,4,01-01-2024,Apartment,39,785.48,"$216,826.00",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
12,5015,5,01-01-2024,Apartment,15,798.50,"$237,680.88",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
19,10035,1,01-01-2024,Apartment,4,633.61,"$166,623.12",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
20,10052,1,01-01-2024,Apartment,6,740.75,"$233,361.41",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
27,10186,1,01-01-2024,Office,23,1201.50,"$399,122.68",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,200381,20,12-01-2025,Apartment,42,811.56,"$225,326.30",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
9993,200404,20,12-01-2025,Apartment,46,1227.49,"$359,645.92",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
9995,200417,20,12-01-2025,Apartment,48,860.80,"$271,177.34",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
9998,200449,20,12-01-2025,Apartment,51,1062.33,"$328,980.19",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None
9999,990014,4,12-01-2025,Apartment,13,733.19,"$217,357.63",Available,None,None,None,None,None,None,None,None,None,None,<NA>,None,None

Observation :
The observation found from missing cells was not because lack of datas, but it is because the `listing_status` which were `available`. Hence the unsold units has no customer data, leading to the missing data.

In [112]:
with pd.option_context('display.max_columns', None):
    display(df.head(10))

,listing_id,tower_number,transaction_date,unit_category,unit_number,floor_area_sqft,sale_price,listing_status,client_ref,client_id,client_type,first_name,last_name,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,1012,1,01-01-2024,Apartment,12,1160.36,"$300,385.62",Sold,C0027,C0027,Individual,Grant,Weber,09-08-1968,M,USA,California,Home,5,Yes,Website
1,1015,1,01-01-2024,Apartment,15,782.25,"$208,930.81",Sold,C0097,C0097,Individual,Franklin,Mack,6/18/1943,M,USA,Virginia,Home,5,Yes,Website
2,1021,1,01-01-2024,Apartment,21,756.21,"$218,585.92",Sold,C0113,C0113,Individual,Arthur,Bray,7/14/1949,M,USA,Utah,Investment,4,No,Agency
3,1030,1,01-01-2024,Apartment,30,743.09,"$246,172.68",Sold,C0141,C0141,Individual,Madalyn,Mercer,6/21/1986,F,USA,California,Home,5,No,Website
4,2016,2,01-01-2024,Apartment,16,701.66,"$212,265.67",Sold,C0146,C0146,Individual,Hazel,Ayers,02-01-1963,M,USA,Colorado,Home,2,No,Website
5,2018,2,01-01-2024,Apartment,18,927.83,"$275,394.25",Sold,C0023,C0023,Individual,Cole,Taylor,12-06-1958,M,USA,California,Home,3,Yes,Website
6,2029,2,01-01-2024,Apartment,29,1109.25,"$310,223.29",Sold,C0040,C0040,Individual,Conner,Huff,3/22/1975,M,USA,Nevada,Home,5,No,Website
7,3006,3,01-01-2024,Apartment,6,1132.06,"$356,506.37",Sold,C0007,C0007,Individual,Xavier,Faulkner,5/24/1947,M,Canada,Quebec,Investment,5,No,Website
8,3026,3,01-01-2024,Apartment,26,670.89,"$212,520.83",Sold,C0082,C0082,Individual,Kaitlin,Owen,12/26/1981,F,USA,Virginia,Investment,5,No,Client
9,3031,3,01-01-2024,Apartment,31,1596.35,"$407,214.29",Sold,C0038,C0038,Individual,Janelle,Espinoza,12/25/1974,F,USA,California,Investment,4,No,Client

### $$ Data Cleaning for Visualisation $$

#### Removing The Unnecessary Columns

In [113]:
df.drop(columns=['client_ref','first_name','last_name','unit_number'], inplace=True)

In [114]:
print(f"REMAINING COLUMNS : {df.shape[1]}")
df.head()

REMAINING COLUMNS : 17

,listing_id,tower_number,transaction_date,unit_category,floor_area_sqft,sale_price,listing_status,client_id,client_type,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel
0,1012,1,01-01-2024,Apartment,1160.36,"$300,385.62",Sold,C0027,Individual,09-08-1968,M,USA,California,Home,5,Yes,Website
1,1015,1,01-01-2024,Apartment,782.25,"$208,930.81",Sold,C0097,Individual,6/18/1943,M,USA,Virginia,Home,5,Yes,Website
2,1021,1,01-01-2024,Apartment,756.21,"$218,585.92",Sold,C0113,Individual,7/14/1949,M,USA,Utah,Investment,4,No,Agency
3,1030,1,01-01-2024,Apartment,743.09,"$246,172.68",Sold,C0141,Individual,6/21/1986,F,USA,California,Home,5,No,Website
4,2016,2,01-01-2024,Apartment,701.66,"$212,265.67",Sold,C0146,Individual,02-01-1963,M,USA,Colorado,Home,2,No,Website

---

#### FEATURE EXTRACTION -- Finding Age Of The Client From DOB
First we have to convert the dates into datetime format

In [115]:
df.dtypes.reset_index()

                  index        0
0            listing_id    int64
1          tower_number    int64
2      transaction_date   object
3         unit_category   object
4       floor_area_sqft  float64
5            sale_price   object
6        listing_status   object
7             client_id   object
8           client_type   object
9         date_of_birth   object
10               gender   object
11              country   object
12               region   object
13  acquisition_purpose   object
14   satisfaction_score    int64
15         loan_applied   object
16     referral_channel   object

Converting `transaction_date` and `date_of_birth` into datetime format

In [116]:
df['transaction_date'] = df['transaction_date'].str.replace('-', '/')
df['date_of_birth'] = df['date_of_birth'].str.replace('-', '/')

In [117]:
# The `errors='coerce'` argument turns invalid dates into NaT (Not a Time)

df['transaction_date'] = pd.to_datetime(df['transaction_date'], format='%m/%d/%Y', errors='coerce')
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='%m/%d/%Y', errors='coerce')

In [118]:
df[['transaction_date', 'date_of_birth']].dtypes.reset_index()

              index               0
0  transaction_date  datetime64[ns]
1     date_of_birth  datetime64[ns]

In [119]:
# Calculating Current Date
current_date = pd.to_datetime('today')

# Calculating Age
df['age'] = np.floor((current_date - df['date_of_birth']).dt.days / 365.25)

In [122]:
df[['age','date_of_birth','transaction_date']].reset_index()

      index   age date_of_birth transaction_date
0         0  57.0    1968-09-08       2024-01-01
1         1  83.0    1943-06-18       2024-01-01
2         2  77.0    1949-07-14       2024-01-01
3         3  40.0    1986-06-21       2024-01-01
4         4  63.0    1963-02-01       2024-01-01
...     ...   ...           ...              ...
9995   9995   nan           NaT       2025-12-01
9996   9996  41.0    1985-06-28       2025-12-01
9997   9997  34.0    1992-01-14       2025-12-01
9998   9998   nan           NaT       2025-12-01
9999   9999   nan           NaT       2025-12-01

[10000 rows x 4 columns]

In [123]:
df[df['age'].isna()]

,listing_id,tower_number,transaction_date,unit_category,floor_area_sqft,sale_price,listing_status,client_id,client_type,date_of_birth,gender,country,region,acquisition_purpose,satisfaction_score,loan_applied,referral_channel,age
11,4039,4,2024-01-01,Apartment,785.48,"$216,826.00",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
12,5015,5,2024-01-01,Apartment,798.50,"$237,680.88",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
19,10035,1,2024-01-01,Apartment,633.61,"$166,623.12",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
20,10052,1,2024-01-01,Apartment,740.75,"$233,361.41",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
27,10186,1,2024-01-01,Office,1201.50,"$399,122.68",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,200381,20,2025-12-01,Apartment,811.56,"$225,326.30",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
9993,200404,20,2025-12-01,Apartment,1227.49,"$359,645.92",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
9995,200417,20,2025-12-01,Apartment,860.80,"$271,177.34",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
9998,200449,20,2025-12-01,Apartment,1062.33,"$328,980.19",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan
9999,990014,4,2025-12-01,Apartment,733.19,"$217,357.63",Available,None,None,NaT,None,None,None,None,<NA>,None,None,nan